{% set name = 'psocake' %}
{% set version = '01.00.15' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lcls-psana/{{ name }}/archive/V01-00-15.tar.gz
  sha256: afef85c5b9cca7daada0478d493c76c13fe3d1c6e09d2c273cf11308d165b92e

build:
  skip: True  # [win or osx]
  number: 1
  script:
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy
    - scipy
    - pandas
    - pyqtgraph
    - pyqt
    - h5py
    - scikit-learn
    - mpi4py
    - scikit-image

test:
  imports:
    - psocake

about:
  home: https://lcls.slac.stanford.edu
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Data analysis software for Free-Electron Lasers'
  description: |
    making data analysis for free-electron lasers a piece of cake.
  doc_url: https://github.com/lcls-psana/psocake/blob/master/README.md  
  dev_url: https://github.com/slaclab/psocake

extra:
  recipe-maintainers:
    - valmar
    - chrisvam
