{% set name = 'psocake' %}
{% set version = '01.00.19' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lcls-psana/{{ name }}/archive/V01-00-19.tar.gz
  sha256: 65f68d4c757ee8057c01f4ab1e88e8fd650801224bbc15c4595eccfb01c69d7a 

build:
  skip: True  # [win or osx]
  number: 2
  script:
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy
    - scipy
    - pandas
    - pyqtgraph
    - pyqt
    - h5py
    - scikit-learn
    - mpi4py
    - scikit-image

test:
  imports:
    - psocake

about:
  home: https://lcls.slac.stanford.edu
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Data analysis software for Free-Electron Lasers'
  description: |
    making data analysis for free-electron lasers a piece of cake.
  doc_url: https://github.com/lcls-psana/psocake/blob/master/README.md  
  dev_url: https://github.com/slaclab/psocake

extra:
  recipe-maintainers:
    - valmar
    - chrisvam
