{% set name = 'psocake' %}
{% set version = '01.00.12' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lcls-psana/{{ name }}/archive/V01-00-12.tar.gz
  sha256: 23678d297f2f5ddd42e0c532f7f00555784c5eebac08d34ef609742f6761ea89

build:
  skip: True  # [win or osx]
  number: 0
  script:
    - "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy
    - scipy
    - pandas
    - pyqtgraph
    - pyqt
    - h5py
    - scikit-learn
    - mpi4py
    - scikit-image

test:
  imports:
    - psocake

about:
  home: https://lcls.slac.stanford.edu
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Data analysis software for Free-Electron Lasers'
  description: |
    making data analysis for free-electron lasers a piece of cake.
  doc_url: https://github.com/lcls-psana/psocake/blob/master/README.md  
  dev_url: https://github.com/slaclab/psocake

extra:
  recipe-maintainers:
    - valmar
    - chrisvam
